### PR TITLE
Add 'explore possibilities' button in project details view

### PR DESCRIPTION
**Pull request by rubentd**
Generate random tokenId and hash and preview a generator iframe
Fix dependency issues

### CODE REVIEW

**Comment by Jbern16** [comment]
@rubentd this is awesome! Would you mind including a screen capture of this working when you get a chance?

**Comment by Jbern16** [comment]
also adding @lyaunzbe as a reviewer to take a look at the generator usage here

**Comment by rubentd** [comment]
> @rubentd this is awesome! Would you mind including a screen capture of this working when you get a chance?

Yes, no problem @Jbern16 

Screen Shot 2022-11-28 at 1 13 13 PM

There's also a demo: http://pbab-demo.s3-website-us-east-1.amazonaws.com/

**Review by Jbern16 — APPROVED** [review]

**Review by Asupkay — APPROVED** [review]

**Comment by jakerockland** [comment]
TYVM for additional review here @Asupkay 

Merging given 2-reviews, but if there is additional post-merge feedback from your end @lyaunzbe we can always add additional iteration.

**Comment by lyaunzbe** [comment]
Somehow missed the initial tag on this, apologies! 

Just reviewed and all looks good from generator utilization side 🙌

**Comment by jakerockland** [comment]
No sweat ser, thank you for TAL!

**Pull request merged**
